@startuml
title Use Case Diagram

rectangle {
usecase "Start Quiz" as UC1
usecase "View Questions" as UC2
usecase "Select Answers" as UC3
usecase "Submit Answers" as UC5
usecase "Submit Results" as UC6
usecase "View Suggestions" as UC7
usecase "View Hint" as UC8

(load splash) ..> UC1
UC1 -->UC2: <<includes>>
UC2 --> UC3: <<includes>>
UC5 <-- UC3: <<includes>>
UC6 --> UC1
UC5 --> UC6: <<includes>>
UC6 --> UC7: <<includes>>
UC3 -> UC8: <<includes>>
UC8 --> UC3: <<includes>>
UC7 --> UC1
}
@enduml